/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employee_management;

import java.awt.Color;
import java.math.BigInteger;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Sudip_Maiti
 */
public class Create_Emp extends javax.swing.JPanel {
String emp_Id;
String emp;
 BigInteger emp_id =null;
    /**
     * Creates new form Create_Emp
     */
    public Create_Emp() {
        initComponents();
        id_create();
        
          fName.setVisible(false);
        L_name.setVisible(false);
        Phone.setVisible(false);
        Email.setVisible(false);
      
        mng_name.setEditable(false);
        mng_id.setEditable(false);
        Emp_id.setEditable(false);
         aaaa.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fName = new javax.swing.JLabel();
        Phone = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        crt_emp = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        L_name = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        aaaa = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        phone3 = new javax.swing.JTextField();
        Emp_id = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        mng_id = new javax.swing.JTextField();
        mng_name = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1122, 767));

        jPanel1.setBackground(new java.awt.Color(14, 73, 181));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        jPanel1.setMaximumSize(new java.awt.Dimension(1122, 765));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel1.setText("Create New Employee !");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 30, 400, -1));

        fName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        fName.setForeground(new java.awt.Color(128, 128, 128));
        fName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fName.setText("First Name");
        jPanel2.add(fName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, 20));

        Phone.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Phone.setForeground(new java.awt.Color(128, 128, 128));
        Phone.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Phone.setText("Phone");
        jPanel2.add(Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 260, 20));

        Email.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Email.setForeground(new java.awt.Color(128, 128, 128));
        Email.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Email.setText("Email");
        jPanel2.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 280, 20));

        crt_emp.setBackground(new java.awt.Color(0, 102, 255));
        crt_emp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Create Employee");
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout crt_empLayout = new javax.swing.GroupLayout(crt_emp);
        crt_emp.setLayout(crt_empLayout);
        crt_empLayout.setHorizontalGroup(
            crt_empLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
        );
        crt_empLayout.setVerticalGroup(
            crt_empLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        jPanel2.add(crt_emp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 560, 50));

        L_name.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        L_name.setForeground(new java.awt.Color(128, 128, 128));
        L_name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        L_name.setText("Last Name");
        jPanel2.add(L_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 220, 20));

        jLabel26.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(128, 128, 128));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("Employee ID");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 90, 20));

        aaaa.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        aaaa.setForeground(new java.awt.Color(128, 128, 128));
        aaaa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        aaaa.setText("Address");
        jPanel2.add(aaaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 70, 20));

        firstname.setBackground(new java.awt.Color(255, 255, 255));
        firstname.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        firstname.setForeground(new java.awt.Color(128, 128, 128));
        firstname.setText("First Name");
        firstname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 204)));
        firstname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstnameFocusLost(evt);
            }
        });
        firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameActionPerformed(evt);
            }
        });
        jPanel2.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 260, 30));

        lastname.setBackground(new java.awt.Color(255, 255, 255));
        lastname.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lastname.setForeground(new java.awt.Color(128, 128, 128));
        lastname.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        lastname.setText("Last Name");
        lastname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 204)));
        lastname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastnameFocusLost(evt);
            }
        });
        lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameActionPerformed(evt);
            }
        });
        jPanel2.add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 280, 30));

        email.setBackground(new java.awt.Color(255, 255, 255));
        email.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        email.setForeground(new java.awt.Color(128, 128, 128));
        email.setText("Email");
        email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 204)));
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 280, 30));

        phone3.setBackground(new java.awt.Color(255, 255, 255));
        phone3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        phone3.setForeground(new java.awt.Color(128, 128, 128));
        phone3.setText("Phone");
        phone3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 204)));
        phone3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phone3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phone3FocusLost(evt);
            }
        });
        jPanel2.add(phone3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 260, 30));

        Emp_id.setBackground(new java.awt.Color(255, 255, 255));
        Emp_id.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        Emp_id.setForeground(new java.awt.Color(0, 0, 0));
        Emp_id.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Emp_id.setText("123456798");
        Emp_id.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 204)));
        Emp_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Emp_idActionPerformed(evt);
            }
        });
        jPanel2.add(Emp_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 260, 30));

        address.setBackground(new java.awt.Color(255, 255, 255));
        address.setColumns(10);
        address.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        address.setForeground(new java.awt.Color(0, 0, 0));
        address.setRows(5);
        address.setText("Address");
        address.setBorder(null);
        address.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        address.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addressFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(address);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 560, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 600, 600));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Georgia", 0, 48)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Welcome !");
        jLabel23.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 260, 70));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add-group (3).png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 440, 310));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Georgia", 1, 30)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("<Html> <p align = center>  CREATE  <br>   EMPLOYEE</p></Html>");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 440, 110));

        mng_id.setBackground(new java.awt.Color(14, 73, 181));
        mng_id.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        mng_id.setForeground(new java.awt.Color(255, 255, 255));
        mng_id.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        mng_id.setToolTipText("");
        mng_id.setBorder(null);
        jPanel1.add(mng_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 290, 30));

        mng_name.setBackground(new java.awt.Color(14, 73, 181));
        mng_name.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        mng_name.setForeground(new java.awt.Color(255, 255, 255));
        mng_name.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        mng_name.setToolTipText("");
        mng_name.setBorder(null);
        jPanel1.add(mng_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 290, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1068, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
 void id_create(){
        Emp_id.setEditable(false);
         try{
            Connection con=DATABASE_CONNECTION.getConnection();
            PreparedStatement ps=con.prepareStatement("select * from id_store");         
            ResultSet rs=ps.executeQuery();
            if(rs.next()){
              //  mng_Id=rs.getString("MNG_ID");
               // System.out.println("MANAGER ID "+mng_Id);
                emp_Id=rs.getString("emp_id");
              //  System.out.println("EMPLOYEE ID "+emp_Id);
              //  Transaction_Id=rs.getString("TRANSACTION_ID");
              //  System.out.println("Transaction_Id "+Transaction_Id);
             //   Product_id=rs.getString("PRODUCT_ID");
               
                rs.close();
                ps.close();
            }else{
                JOptionPane.showMessageDialog(null, "NOTHING FOUND IN DATABASE!!!!!!");
            }
            con.close();
           }
        catch(Exception e){System.out.println(e);}
         
        emp_id = new BigInteger(emp_Id);
        BigInteger nxt = new BigInteger("1");
      //  System.out.println("!!!!!!!!!!!!!!!!!!!!!!!!!!"+emp_Id);
      //  System.out.println("#################"+emp_id);
        emp_id = emp_id.add(nxt);
     //   System.out.println("%%%%%%%%%%%%%%%%%%%%%%"+emp_id);
        emp = "ERP_E"+emp_id.toString();
    //    System.out.println("%%%%%%%%%%%%%%%%%%%%%%"+emp);
     //   System.out.println("++++++++++++++++"+emp_id);
        Emp_id.setText(emp);
    }
    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        // TODO add your handling code here:
        String fName = firstname.getText();
        String lName = lastname.getText();
        String ph = phone3.getText();
        String mail = email.getText();

        String add = address.getText();
        String empp=Emp_id.getText();

        if(fName.equals("First Name")||lName.equals("Last Name")||ph.equals("Phone")||mail.equals("Email")||add.equals("Address")||fName.equals("")||lName.equals("")||ph.equals("")||mail.equals("")||add.equals("")){
            // JOptionPane.showMessageDialog(this, "");
            new Warning("Fill up all field first").setVisible(true);
        }else{
            int i = ADD_NEW_EMP_DATAOBEJECT.create_emp(fName, lName, mail, ph,empp, add);

            int j = ID_STORE_FETCH.insert_id(emp_id.toString());
            if(i>0 || j>0){
                System.out.println("Data inserted");
                Succes su= new Succes();
                su.ot("Employee Created Succesfully");
                su.setVisible(true);

                firstname.setText("");
                lastname.setText("");
                phone3.setText("");
                email.setText("");

                address.setText("");

            }else{
                //  System.out.println("Data NOT inserted");
                new Error("Please Try Again!").setVisible(true);
            }

        }

    }//GEN-LAST:event_jLabel28MouseClicked

    private void firstnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnameFocusGained
        // TODO add your handling code here:
        if(firstname.getText().equals("First Name")){
            fName.setVisible(true);
            firstname.setText("");
            firstname.setForeground(new Color(000,000,000));
        }
    }//GEN-LAST:event_firstnameFocusGained

    private void firstnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnameFocusLost
        // TODO add your handling code here:
        if(firstname.getText().equals("")){
            fName.setVisible(false);
            firstname.setText("First Name");
            firstname.setForeground(new Color(128,128,128));
        }else{
            fName.setVisible(true);
        }
    }//GEN-LAST:event_firstnameFocusLost

    private void firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameActionPerformed

    private void lastnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnameFocusGained
        // TODO add your handling code here:
        if(lastname.getText().equals("Last Name")){
            L_name.setVisible(true);
            lastname.setText("");
            lastname.setForeground(new Color(000,000,000));
        }
    }//GEN-LAST:event_lastnameFocusGained

    private void lastnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnameFocusLost
        // TODO add your handling code here:
        if(lastname.getText().equals("")){
            L_name.setVisible(false);
            lastname.setText("Last Name");
            lastname.setForeground(new Color(128,128,128));
        }else{
            L_name.setVisible(true);
        }
    }//GEN-LAST:event_lastnameFocusLost

    private void lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameActionPerformed

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
        // TODO add your handling code here:
        if(email.getText().equals("Email")){
            Email.setVisible(true);
            email.setText("");
            email.setForeground(new Color(000,000,000));
        }
    }//GEN-LAST:event_emailFocusGained

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        // TODO add your handling code here:
        if(email.getText().equals("")){
            Email.setVisible(false);
            email.setText("Email");
            email.setForeground(new Color(128,128,128));
        }else{
            Email.setVisible(true);
        }
    }//GEN-LAST:event_emailFocusLost

    private void phone3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phone3FocusGained
        // TODO add your handling code here:
        if(phone3.getText().equals("Phone")){
            Phone.setVisible(true);
            phone3.setText("");
            phone3.setForeground(new Color(000,000,000));
        }
    }//GEN-LAST:event_phone3FocusGained

    private void phone3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phone3FocusLost
        // TODO add your handling code here:
        if(phone3.getText().equals("")){
            Phone.setVisible(false);
            phone3.setText("Phone");
            phone3.setForeground(new Color(128,128,128));
        }else{
            Phone.setVisible(true);
        }
    }//GEN-LAST:event_phone3FocusLost

    private void Emp_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Emp_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Emp_idActionPerformed

    private void addressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressFocusGained
        // TODO add your handling code here:
        if(address.getText().equals("Address")){
            aaaa.setVisible(true);
            address.setText("");
            address.setForeground(new Color(000,000,000));
        }
    }//GEN-LAST:event_addressFocusGained

    private void addressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressFocusLost
        // TODO add your handling code here:
        if(address.getText().equals("")){
            aaaa.setVisible(false);
            address.setText("Address");
            address.setForeground(new Color(128,128,128));
        }else{
            aaaa.setVisible(true);
        }
    }//GEN-LAST:event_addressFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Email;
    private javax.swing.JTextField Emp_id;
    private javax.swing.JLabel L_name;
    private javax.swing.JLabel Phone;
    private javax.swing.JLabel aaaa;
    private javax.swing.JTextArea address;
    private javax.swing.JPanel crt_emp;
    private javax.swing.JTextField email;
    private javax.swing.JLabel fName;
    private javax.swing.JTextField firstname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastname;
    private javax.swing.JTextField mng_id;
    private javax.swing.JTextField mng_name;
    private javax.swing.JTextField phone3;
    // End of variables declaration//GEN-END:variables
}
