/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employee_management;


import com.sun.media.sound.DLSSoundbank;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author ganesh_pradhan
 */
public class Login extends javax.swing.JFrame {
    
    
    public void wel(String val){
        String v= "0";
        v=val;
        if(v.equals("2")){
            web.setVisible(true);
        we.setVisible(false);
        }else{
            we.setVisible(true);
        web.setVisible(false);
        }
        
    }

    /**
     * Creates new form login3
     */
    public Login() {
        initComponents();
        pass.setEchoChar((char)0);
        pt.setVisible(false);
        we.setVisible(true);
        web.setVisible(false);
        
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        web = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        pass = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        hide = new javax.swing.JLabel();
        show = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        pt = new javax.swing.JLabel();
        e1 = new javax.swing.JLabel();
        we = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Close_bb = new javax.swing.JPanel();
        Close_b = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(47, 68, 187));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(47, 68, 187)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Tablet login-rafiki (1).png"))); // NOI18N
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 600, 550));

        web.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        web.setForeground(new java.awt.Color(47, 68, 187));
        web.setText("Welcome Back!");
        jPanel5.add(web, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(47, 68, 187));
        jLabel3.setText("Login to Continue your Dashboard");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 300, 30));

        jLabel12.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setText("Forgot Password?");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 110, 40));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(47, 68, 187)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-user-41.png"))); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 50));

        email.setBackground(new java.awt.Color(255, 255, 255));
        email.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        email.setForeground(new java.awt.Color(128, 128, 128));
        email.setText("Enter Username");
        email.setBorder(null);
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });
        jPanel3.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 10, 290, 30));

        jPanel5.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 350, 50));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(47, 68, 187)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pass.setBackground(new java.awt.Color(255, 255, 255));
        pass.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        pass.setForeground(new java.awt.Color(128, 128, 128));
        pass.setText("Enter Your Password");
        pass.setBorder(null);
        pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passFocusLost(evt);
            }
        });
        jPanel4.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 250, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/lock.png"))); // NOI18N
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 50));

        hide.setForeground(new java.awt.Color(102, 102, 102));
        hide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/visibility (1).png"))); // NOI18N
        hide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hideMouseClicked(evt);
            }
        });
        jPanel4.add(hide, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 40, 30));

        show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/visibility.png"))); // NOI18N
        show.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
        });
        jPanel4.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 40, 30));

        jPanel5.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 350, 50));

        jPanel6.setBackground(new java.awt.Color(47, 68, 187));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Consolas", 1, 28)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Login");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 50));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 350, -1));

        pt.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        pt.setForeground(new java.awt.Color(128, 128, 128));
        pt.setText("Enter Your Password");
        jPanel5.add(pt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 230, 30));

        e1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        e1.setForeground(new java.awt.Color(128, 128, 128));
        e1.setText("Enter Username");
        jPanel5.add(e1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 190, 30));

        we.setFont(new java.awt.Font("Arial", 1, 40)); // NOI18N
        we.setForeground(new java.awt.Color(47, 68, 187));
        we.setText("Welcome!");
        jPanel5.add(we, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 50));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 58, 1057, 582));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Close_bb.setBackground(new java.awt.Color(255, 255, 255));
        Close_bb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Close_b.setFont(new java.awt.Font("Dialog", 1, 40)); // NOI18N
        Close_b.setForeground(new java.awt.Color(255, 51, 0));
        Close_b.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Close_b.setText("×");
        Close_b.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close_b.setPreferredSize(new java.awt.Dimension(40, 40));
        Close_b.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Close_bMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Close_bMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Close_bMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Close_bbLayout = new javax.swing.GroupLayout(Close_bb);
        Close_bb.setLayout(Close_bbLayout);
        Close_bbLayout.setHorizontalGroup(
            Close_bbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Close_bbLayout.createSequentialGroup()
                .addComponent(Close_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Close_bbLayout.setVerticalGroup(
            Close_bbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Close_b, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.add(Close_bb, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 0, 40, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 370));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 710));

        setSize(new java.awt.Dimension(1200, 709));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        Email_Verification ev = new Email_Verification();
        ev.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void hideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMouseClicked
        // TODO add your handling code here:
        hide.setVisible(false);
        show.setVisible(true);
        pass.setEchoChar((char)0);
    }//GEN-LAST:event_hideMouseClicked

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
        // TODO add your handling code here:
        show.setVisible(false);
        hide.setVisible(true);
        pass.setEchoChar('*');
    }//GEN-LAST:event_showMouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        //        com.raven.main.Main sa = new com.raven.main.Main();
        //        sa.setVisible(true);
        //        this.dispose();

        String p_email = email.getText();
        String p_pass = pass.getText();
        String name= null;
        String mng_Id = null;
        String eml= null;
        String phone = null;
        try {
            if(p_email.equals("")||p_pass.equals("")){
              new Warning("Fill up all field first").setVisible(true);
                
               // JOptionPane.showMessageDialog(this, "Fill up all field first","Error",JOptionPane.ERROR_MESSAGE);
            }else{
                //  Data fetch from database
                String sql = "Select * from admin Where mng_id = ?";
                Connection con=DATABASE_CONNECTION.getConnection();
                PreparedStatement ps=con.prepareStatement(sql);
                ps.setString(1,p_email);
                ResultSet rs=ps.executeQuery();
                if(rs.next()){
                    //
                    eml =rs.getString("email");
                    //   System.out.println("EMAILLLLLLLL "+eml);
                    phone =rs.getString("Phone");
                    //   System.out.println("EMAILLLLLLLL "+phone);
                    String fname =rs.getString("fname");
                    //  System.out.println("FIRST NAME "+fname);
                    String lname =rs.getString("lname");
                    // System.out.println("LAST NAME "+lname);
                    name = fname+" "+lname;
                    // System.out.println("FULL NAME "+name);
                    mng_Id =rs.getString("mng_id");
                    // System.out.println("MNGGGGGGGGGGGGG "+mng_Id);
                    rs.close();
                    ps.close();

                    try{
                        if(!"".equals(REGISTRATION_DATAOBEJECT.validate(p_email, p_pass))){

                            String ret = REGISTRATION_DATAOBEJECT.validate(p_email, p_pass);
                            if(ret=="yess"){
                                //String timeee = time;
                                // System.out.println("11111111111111" +timeee);
                                // MAN_SEASION_DATAOBJECT.man_isert_session(name,mng_Id,phone,eml,timeee,"",date,"");
                                email.setForeground(Color.GREEN);
                                pass.setForeground(Color.GREEN);
                           Succes sc= new Succes();
                           sc.ss("Login Succesfully.","home");
                           sc.vali(name, mng_Id, eml, phone);
                           sc.setVisible(true);

                                
                                this.dispose();
                                //    System.out.println("2222222222222222" +timeee);

                                // dm.mngname(name,mng_Id,eml,phone,date,timeee);

                            }else  if(ret=="cp"){
                                //String timeee = time;
                                // System.out.println("11111111111111" +timeee);
                                // MAN_SEASION_DATAOBJECT.man_isert_session(name,mng_Id,phone,eml,timeee,"",date,"");
                                email.setForeground(Color.GREEN);
                                pass.setForeground(Color.GREEN);
                                //  JOptionPane.showMessageDialog(null,"This's Your first login", "So You need to change the password first.", JOptionPane.PLAIN_MESSAGE);
                             //   JOptionPane.showMessageDialog(null, "So You need to change the password first.","This's Your first login", JOptionPane.INFORMATION_MESSAGE);
//new Warning("<html><p align= center > This's Your first login. So You need to change the password first.</p> </html>");
Succes su = new Succes();
su.ss("<html><p align= center > This's Your first login.<br> So You need to change the password first.</p> </html>", "cp");
su.setVisible(true);



                                su.vali(name, mng_Id, eml, phone);
                                this.dispose();
                                //    System.out.println("2222222222222222" +timeee);

                                // dm.mngname(name,mng_Id,eml,phone,date,timeee);

                            }else{
                                email.setForeground(Color.RED);
                                pass.setForeground(Color.RED);
                                new Error("Enter Correct Details").setVisible(true);
                             //   JOptionPane.showMessageDialog(null,"Enter Correct Details", "Login Error", JOptionPane.ERROR_MESSAGE);

                                //                email.setText("Manager ID");
                                //                pass.setText("Password");
                                //                pass.setEchoChar((char)0);
                                //                email.setForeground(new Color(128,128,128));
                                //                pass.setForeground(new Color(128,128,128));
                            }
                        }
                    }catch (Exception e){
                        System.out.println("Exception -"+e);
                    }
                }else{
                    new Warning("Enter Correct User Name").setVisible(true);
                    //JOptionPane.showMessageDialog(null, "Enter Correct User Name","Login Error",JOptionPane.ERROR_MESSAGE);
                    //  System.out.println("Enter Correct User Name");
                }
            }
        }catch(Exception e){
            System.out.println("error"+e);
        }
    }//GEN-LAST:event_jLabel13MouseClicked

    private void Close_bMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close_bMouseClicked
        // TODO add your handling code here:
        int Yes = JOptionPane.showConfirmDialog(null, "Are Your Sure Want to Close This Application ?");
        if(Yes == 0){

            this.dispose();
        }else{
            int No=0;
            if (No == 0){
            }
        }
    }//GEN-LAST:event_Close_bMouseClicked

    private void Close_bMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close_bMouseEntered
        // TODO add your handling code here:
        Close_bb.setBackground(new Color(255, 0, 0));
        Close_b.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_Close_bMouseEntered

    private void Close_bMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Close_bMouseExited
        // TODO add your handling code here:
        Close_bb.setBackground(new Color(255, 255, 255));
        Close_b.setForeground(new Color(255,0,0));
    }//GEN-LAST:event_Close_bMouseExited

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
        // TODO add your handling code here:
        if(email.getText().equals("Enter Username")){
           e1.setVisible(true);
            e1.setForeground( Color.decode("#2F44BB"));
            email.setText("");
            email.setForeground( Color.decode("#2F44BB"));
        }
    }//GEN-LAST:event_emailFocusGained

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        // TODO add your handling code here:
          if(email.getText().equals("")){
            e1.setVisible(false);
            email.setText("Enter Username");
           email.setForeground(Color.decode("#808080"));
        }else{
            e1.setVisible(true);
        }
    }//GEN-LAST:event_emailFocusLost

    private void passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFocusGained
        // TODO add your handling code here:
         if(pass.getText().equals("Enter Your Password")){
            pt.setVisible(true);
            pt.setForeground( Color.decode("#2F44BB"));
            pass.setText("");
            pass.setEchoChar('*');
            pass.setForeground(Color.decode("#2F44BB"));
        }
    }//GEN-LAST:event_passFocusGained

    private void passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFocusLost
        // TODO add your handling code here:
          if(pass.getText().equals("")){
            pt.setVisible(false);
            pass.setText("Enter Your Password");
            pass.setEchoChar((char)0);
            pass.setForeground(Color.decode("#808080"));
        }else{
            pass.setVisible(true);
        }
    }//GEN-LAST:event_passFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Close_b;
    private javax.swing.JPanel Close_bb;
    private javax.swing.JLabel e1;
    private javax.swing.JTextField email;
    private javax.swing.JLabel hide;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel pt;
    private javax.swing.JLabel show;
    private javax.swing.JLabel we;
    private javax.swing.JLabel web;
    // End of variables declaration//GEN-END:variables
}
