/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employee_management;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Sudip_Maiti
 */
public class Update_Cus extends javax.swing.JPanel {
 String Epp="";
    public void emp_id(String ee){
        Epp=ee;
    }
    /**
     * Creates new form Update_Emp
     */
    public Update_Cus() {
        initComponents();
        
        
         fName.setVisible(false);
        L_name.setVisible(false);
        Phone.setVisible(false);
        Email.setVisible(false);
       aaaa.setVisible(false);
       
        Emp_id.setEditable(false);
        
        
        
        
        fName1.setVisible(false);
        //System.out.println("empp"+Epp);
        if(Epp!=""){
        update();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        fName = new javax.swing.JLabel();
        Phone = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        crt_emp = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        L_name = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        aaaa = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        phone3 = new javax.swing.JTextField();
        Emp_id = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        address1 = new javax.swing.JTextArea();
        aaaa1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        serch = new javax.swing.JTextField();
        fName1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        fName.setForeground(new java.awt.Color(128, 128, 128));
        fName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fName.setText("First Name");
        jPanel2.add(fName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 140, 20));

        Phone.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Phone.setForeground(new java.awt.Color(128, 128, 128));
        Phone.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Phone.setText("Phone");
        jPanel2.add(Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 260, 20));

        Email.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Email.setForeground(new java.awt.Color(128, 128, 128));
        Email.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Email.setText("Email");
        jPanel2.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 280, 20));

        crt_emp.setBackground(new java.awt.Color(0, 102, 255));
        crt_emp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Update");
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout crt_empLayout = new javax.swing.GroupLayout(crt_emp);
        crt_emp.setLayout(crt_empLayout);
        crt_empLayout.setHorizontalGroup(
            crt_empLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
        );
        crt_empLayout.setVerticalGroup(
            crt_empLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        jPanel2.add(crt_emp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 550, 50));

        L_name.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        L_name.setForeground(new java.awt.Color(128, 128, 128));
        L_name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        L_name.setText("Last Name");
        jPanel2.add(L_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 220, 20));

        jLabel26.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(128, 128, 128));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("Customer ID");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 90, 20));

        aaaa.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        aaaa.setForeground(new java.awt.Color(128, 128, 128));
        aaaa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        aaaa.setText("Address");
        jPanel2.add(aaaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 70, 20));

        firstname.setBackground(new java.awt.Color(255, 255, 255));
        firstname.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        firstname.setForeground(new java.awt.Color(128, 128, 128));
        firstname.setText("First Name");
        firstname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 204)));
        firstname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstnameFocusLost(evt);
            }
        });
        jPanel2.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 260, 30));

        lastname.setBackground(new java.awt.Color(255, 255, 255));
        lastname.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lastname.setForeground(new java.awt.Color(128, 128, 128));
        lastname.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        lastname.setText("Last Name");
        lastname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 204)));
        lastname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastnameFocusLost(evt);
            }
        });
        lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameActionPerformed(evt);
            }
        });
        jPanel2.add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 280, 30));

        email.setBackground(new java.awt.Color(255, 255, 255));
        email.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        email.setForeground(new java.awt.Color(128, 128, 128));
        email.setText("Email");
        email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 204)));
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 280, 30));

        phone3.setBackground(new java.awt.Color(255, 255, 255));
        phone3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        phone3.setForeground(new java.awt.Color(128, 128, 128));
        phone3.setText("Phone");
        phone3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 204)));
        phone3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phone3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phone3FocusLost(evt);
            }
        });
        jPanel2.add(phone3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 260, 30));

        Emp_id.setBackground(new java.awt.Color(255, 255, 255));
        Emp_id.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        Emp_id.setForeground(new java.awt.Color(0, 0, 0));
        Emp_id.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Emp_id.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 153, 204)));
        Emp_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Emp_idActionPerformed(evt);
            }
        });
        jPanel2.add(Emp_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 260, 30));

        jScrollPane1.setBorder(null);

        address.setBackground(new java.awt.Color(255, 255, 255));
        address.setColumns(10);
        address.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        address.setForeground(new java.awt.Color(0, 0, 0));
        address.setRows(5);
        address.setText("Address");
        address.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 102, 255)));
        address.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        address.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addressFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(address);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 244, 550, -1));

        jScrollPane2.setBorder(null);

        address1.setBackground(new java.awt.Color(255, 255, 255));
        address1.setColumns(10);
        address1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        address1.setForeground(new java.awt.Color(0, 0, 0));
        address1.setRows(5);
        address1.setText("Service Description");
        address1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 102, 255)));
        address1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        address1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                address1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                address1FocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(address1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 550, 90));

        aaaa1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        aaaa1.setForeground(new java.awt.Color(128, 128, 128));
        aaaa1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        aaaa1.setText("Service Description");
        jPanel2.add(aaaa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 150, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 610, 540));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Georgia", 0, 48)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Welcome !");
        jLabel23.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 290, 70));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/update-business-user.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 420, 310));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Georgia", 1, 30)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("CUSTOMER");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 410, 50));

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Georgia", 1, 30)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("UPDATE");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 410, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Update Customer !");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 400, -1));

        serch.setBackground(new java.awt.Color(255, 255, 255));
        serch.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        serch.setForeground(new java.awt.Color(128, 128, 128));
        serch.setText("Serch Customer by Customer ID");
        serch.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 102, 255)));
        serch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                serchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                serchFocusLost(evt);
            }
        });
        jPanel3.add(serch, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 320, 30));

        fName1.setFont(new java.awt.Font("Consolas", 1, 21)); // NOI18N
        fName1.setForeground(new java.awt.Color(128, 128, 128));
        fName1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fName1.setText("Serch Customer by Customer ID");
        jPanel3.add(fName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 390, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/magnifying-glass.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 102, 255)));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 46, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 610, 140));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1059, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
public void update(){
       
       try {
        
             //Data fetch from database
            String sql = "Select * From cus Where cus_id = '"+Epp+"'";
            Connection con=DATABASE_CONNECTION.getConnection();
            PreparedStatement ps=con.prepareStatement(sql);
          //  ps.setString(1,"ERP_E1002");
            ResultSet rs=ps.executeQuery();
            if(rs.next()){
                String emp_id =rs.getString("cus_id");
                String f_name =rs.getString("cus_fname");
                // System.out.println("EMpppppp "+f_name);
                String l_name =rs.getString("cus_lname");
                // System.out.println("pppnnn "+l_name);
                String Phone =rs.getString("cus_ph");
                 
                String Email =rs.getString("cus_eml");
               // System.out.println("emlllll "+l_name);
                String Address =rs.getString("cus_adde");
                  String sev =rs.getString("cus_servic");
                firstname.setText(f_name);
                
                lastname.setText(l_name);
                
                phone3.setText(Phone);
                  Emp_id.setText(emp_id);
                email.setText(Email);
               address.setText(Address);
                address1.setText(sev);
                
               // JOptionPane.showMessageDialog(this, "Product Found");
                
               
                rs.close();
                ps.close();
            }else{
               new Warning("Enter Correct Customer Id").setVisible(true);
               // System.out.println("Enter Correct Employee Id");
            }
        }catch(Exception e){
            System.out.println("error"+e);
        }
           
    }
    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        // TODO add your handling code here:
        String fName = firstname.getText();
        String lName = lastname.getText();
        String ph = phone3.getText();
        String mail = email.getText();

        String add = address.getText();
        String empp= Emp_id.getText();
         String servv= address1.getText();
        

        if(fName.equals("First Name")||lName.equals("Last Name")||ph.equals("Phone")||mail.equals("Email")||add.equals("Address")||servv.equals("Service Description")||servv.equals("")||fName.equals("")||lName.equals("")||ph.equals("")||mail.equals("")||add.equals("")){
            // JOptionPane.showMessageDialog(this, "");
            new Warning("Fill up all field first").setVisible(true);
        }else{

            int i=0;
            try{
                Connection con=DATABASE_CONNECTION.getConnection();
                PreparedStatement ps=con.prepareStatement("UPDATE `cus` SET `cus_fname`='"+fName+"',`cus_lname`='"+lName+"',`cus_ph`='"+ph+"',`cus_eml`='"+mail+"',`cus_adde`='"+add+"',`cus_servic`='"+servv+"' where cus_id ='"+empp+"'");
                i=ps.executeUpdate();
                con.close();
            }catch(Exception e){
                System.out.println(e);
            }
            // System.out.println("!!!!!!!!!!!!!!!!!!!!!!!!!!"+i);

            if(i>0){
                Succes su=new Succes();
                su.ot("Customer Profile Update Sucessfully ");
                su.setVisible(true);

                // JOptionPane.showMessageDialog(this, "Employee Profile Update Sucessfully ");

            }else{
                new Error("Please Try Again").setVisible(true);
                // JOptionPane.showMessageDialog(this, "Employee Profile Not Update Sucessfully");
            }
        }

    }//GEN-LAST:event_jLabel28MouseClicked

    private void firstnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnameFocusGained
        // TODO add your handling code here:
        if(firstname.getText().equals("First Name")){
            fName.setVisible(true);
            firstname.setText("");
            firstname.setForeground(new Color(000,000,000));
        }
    }//GEN-LAST:event_firstnameFocusGained

    private void firstnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnameFocusLost
        // TODO add your handling code here:
        if(firstname.getText().equals("")){
            fName.setVisible(false);
            firstname.setText("First Name");
            firstname.setForeground(new Color(128,128,128));
        }else{
            fName.setVisible(true);
        }
    }//GEN-LAST:event_firstnameFocusLost

    private void lastnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnameFocusGained
        // TODO add your handling code here:
        if(lastname.getText().equals("Last Name")){
            L_name.setVisible(true);
            lastname.setText("");
            lastname.setForeground(new Color(000,000,000));
        }
    }//GEN-LAST:event_lastnameFocusGained

    private void lastnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnameFocusLost
        // TODO add your handling code here:
        if(lastname.getText().equals("")){
            L_name.setVisible(false);
            lastname.setText("Last Name");
            lastname.setForeground(new Color(128,128,128));
        }else{
            L_name.setVisible(true);
        }
    }//GEN-LAST:event_lastnameFocusLost

    private void lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameActionPerformed

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
        // TODO add your handling code here:
        if(email.getText().equals("Email")){
            Email.setVisible(true);
            email.setText("");
            email.setForeground(new Color(000,000,000));
        }
    }//GEN-LAST:event_emailFocusGained

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        // TODO add your handling code here:
        if(email.getText().equals("")){
            Email.setVisible(false);
            email.setText("Email");
            email.setForeground(new Color(128,128,128));
        }else{
            Email.setVisible(true);
        }
    }//GEN-LAST:event_emailFocusLost

    private void phone3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phone3FocusGained
        // TODO add your handling code here:
        if(phone3.getText().equals("Phone")){
            Phone.setVisible(true);
            phone3.setText("");
            phone3.setForeground(new Color(000,000,000));
        }
    }//GEN-LAST:event_phone3FocusGained

    private void phone3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phone3FocusLost
        // TODO add your handling code here:
        if(phone3.getText().equals("")){
            Phone.setVisible(false);
            phone3.setText("Phone");
            phone3.setForeground(new Color(128,128,128));
        }else{
            Phone.setVisible(true);
        }
    }//GEN-LAST:event_phone3FocusLost

    private void Emp_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Emp_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Emp_idActionPerformed

    private void addressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressFocusGained
        // TODO add your handling code here:
        if(address.getText().equals("Address")){
            aaaa.setVisible(true);
            address.setText("");
            address.setForeground(new Color(000,000,000));
        }
    }//GEN-LAST:event_addressFocusGained

    private void addressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressFocusLost
        // TODO add your handling code here:
         if(address.getText().equals("")){
            aaaa.setVisible(false);
            address.setText("Phone");
           address.setForeground(new Color(128,128,128));
        }else{
            aaaa.setVisible(true);
        }
    }//GEN-LAST:event_addressFocusLost

    private void serchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_serchFocusGained
         if(serch.getText().equals("Serch Customer by Customer ID")){
            fName1.setVisible(true);
            serch.setText("");
            serch.setForeground(new Color(000,000,000));
        }
    }//GEN-LAST:event_serchFocusGained

    private void serchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_serchFocusLost
        // TODO add your handling code here:
          if(serch.getText().equals("")){
            fName1.setVisible(false);
            serch.setText("Serch Customer by Customer ID");
            serch.setForeground(new Color(128,128,128));
        }else{
            fName1.setVisible(true);
        }
    }//GEN-LAST:event_serchFocusLost

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        
         String em_id = serch.getText();
      try {
        
             //Data fetch from database
            String sql = "Select * From cus Where cus_id = '"+em_id+"'";
            Connection con=DATABASE_CONNECTION.getConnection();
            PreparedStatement ps=con.prepareStatement(sql);
          //  ps.setString(1,"ERP_E1002");
            ResultSet rs=ps.executeQuery();
            if(rs.next()){
                String emp_id =rs.getString("cus_id");
                String f_name =rs.getString("cus_fname");
                // System.out.println("EMpppppp "+f_name);
                String l_name =rs.getString("cus_lname");
                // System.out.println("pppnnn "+l_name);
                String Phone =rs.getString("cus_ph");
                 
                String Email =rs.getString("cus_eml");
               // System.out.println("emlllll "+l_name);
                String Address =rs.getString("cus_adde");
                  String sev =rs.getString("cus_servic");
                firstname.setText(f_name);
                
                lastname.setText(l_name);
                
                phone3.setText(Phone);
                  Emp_id.setText(emp_id);
                email.setText(Email);
               address.setText(Address);
                address1.setText(sev);
                
               // JOptionPane.showMessageDialog(this, "Product Found");
                
               
                rs.close();
                ps.close();
            }else{
               new Warning("Enter Correct Customer Id").setVisible(true);
               // System.out.println("Enter Correct Employee Id");
            }
        }catch(Exception e){
            System.out.println("error"+e);
        }       
    }//GEN-LAST:event_jLabel2MouseClicked

    private void address1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_address1FocusGained
        // TODO add your handling code here:
         if(address1.getText().equals("Service Description")){
            aaaa1.setVisible(true);
            address1.setText("");
            address1.setForeground(new Color(000,000,000));
        }
        
    }//GEN-LAST:event_address1FocusGained

    private void address1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_address1FocusLost
        // TODO add your handling code here:
         if(address1.getText().equals("")){
            aaaa1.setVisible(false);
            address1.setText("Service Description");
            address1.setForeground(new Color(128,128,128));
        }else{
            aaaa1.setVisible(true);
        }
    }//GEN-LAST:event_address1FocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Email;
    private javax.swing.JTextField Emp_id;
    private javax.swing.JLabel L_name;
    private javax.swing.JLabel Phone;
    private javax.swing.JLabel aaaa;
    private javax.swing.JLabel aaaa1;
    private javax.swing.JTextArea address;
    private javax.swing.JTextArea address1;
    private javax.swing.JPanel crt_emp;
    private javax.swing.JTextField email;
    private javax.swing.JLabel fName;
    private javax.swing.JLabel fName1;
    private javax.swing.JTextField firstname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lastname;
    private javax.swing.JTextField phone3;
    private javax.swing.JTextField serch;
    // End of variables declaration//GEN-END:variables
}
